spring:
  datasource:
    url: <url>
    username: <username>
    password: <password>
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hateoas:
    use-hal-as-default-json-media-type: false

